# The logstash instance we'll be shipping the logs to (which then ships
# them else where)
logstash:
  image: ardinor/simplelogstash
  ports:
    # Map port for host itself to use
    - "127.0.0.1:5545:5545"
    - "127.0.0.1:5545:5545/udp"
  #environment:
  #  - REDIS_HOST
  #  - REDIS_PORT
  hostname: logstash
  restart: always

# Apparently logspout needs to either start first or all other
# containers need to be restarted after it's up for it to get logs
# since we don't actually want the logs of the logstash instance (or do we?)
logspout:
  image: gliderlabs/logspout:latest
  volumes: /var/run/docker.sock:/tmp/docker.sock
  # Send it to the simplelogstash instance
  # Since we'll link to the logstash instance and entry will be added to
  # /etc/hosts for it
  command: syslog://logstash:5544
  links:
    - logstash
  hostname: logspout
  restart: always
